### ISSUE TITLE
EnhanceNet convert .zip to lmdb Error

### ISSUE THREAD

**Issue by memoiry** [PatWie/tensorflow-recipes#1]
Hi, thanks for sharing this wonderful project!

I have been trying to reproduce your `EnhanceNet` code and have downloaded the `train2017.zip` file, after that, I run `python data_sampler.py --lmdb train2017.lmdb --input train2017.zip --debug` and got stuck in the data preprocessing section.

my environment is python2.7.

```bash
(python2.7) wenge@cad-gpu-144:~/xgd/grad/tensorpack-recipes/EnhanceNet$ PYTHONENCODING=utf-8 python data_sampler.py --lmdb train2017.lmdb --input train2017.zip --debug
Traceback (most recent call last):
  File "data_sampler.py", line 112, in <module>
    for i in ds.get_data():
  File "/home/wenge/pythonenv/python2.7/local/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 265, in get_data
    for dp in self.ds.get_data():
  File "/home/wenge/pythonenv/python2.7/local/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 265, in get_data
    for dp in self.ds.get_data():
  File "/home/wenge/pythonenv/python2.7/local/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 266, in get_data
    ret = self.func(copy(dp))  # shallow copy the list
  File "/home/wenge/pythonenv/python2.7/local/lib/python2.7/site-packages/tensorpack/dataflow/common.py", line 292, in f
    r = func(dp[index])
  File "data_sampler.py", line 55, in func
    img = cv2.imdecode(im_data, cv2.IMREAD_COLOR)
TypeError: buf is not a numpy array, neither a scalar
```

Can you please suggest any idea to fix this? Thanks!

**Comment by PatWie** [comment]
Thank you for reporting. This bug was introduced during refactoring. It is fixed now by 72692e28eb1f363e82280a7897780c1f9f0ac5a1. Let me know if there some other issues.
